//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_ID { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Age { get; set; }
        public string Admin_Telephone { get; set; }
        public string Admin_IdentityID { get; set; }
    }
}
