//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string Address { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> ClearOrNot { get; set; }
        public Nullable<bool> ReceiptOrNot { get; set; }
        public int OrderID { get; set; }
        public string BookID { get; set; }
        public int CustomID { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string Custom_Telephone { get; set; }
    }
}
