//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public int Purchase_ID { get; set; }
        public int Admin_ID { get; set; }
        public string Book_ID { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Purchase_Time { get; set; }
    }
}
