//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int BookId { get; set; }
        public string AuthorName { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string BookCoverUrl { get; set; }
        public int OrderID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Num { get; set; }
    }
}
